FROM nginx:latest

COPY index.html /usr/share/nginx/html/index.html





# FROM python:3.8

# WORKDIR /code

# COPY index.html /usr/share/nginx/html/index.html

# RUN pip install -r requirements.txt

# EXPOSE 8000

# CMD gunicorn my_proj.wsgi -b 0.0.0.0:8000